export enum NotificationType {
  SESSION_SCHEDULED = 'SESSION_SCHEDULED',
  SESSION_STARTED = 'SESSION_STARTED',
  SESSION_UPDATED = 'SESSION_UPDATED',
  SESSION_CANCELLED = 'SESSION_CANCELLED',
  ATTENDANCE_RECORDED = 'ATTENDANCE_RECORDED',
}
